/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  BatchApi,
  CheckoutV2GenerationApi,
  CheckoutGenerationApi,
  FilesApi,
  HelpersApi,
  PaymentApi,
  PaymentsApiInboundApi,
  PaymentsApiOutboundApi,
  StatusApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { PeachPaymentsCustom } from "./client-custom";

export class PeachPayments extends PeachPaymentsCustom {
  readonly batch: BatchApi;
  readonly checkoutV2Generation: CheckoutV2GenerationApi;
  readonly checkoutGeneration: CheckoutGenerationApi;
  readonly files: FilesApi;
  readonly helpers: HelpersApi;
  readonly payment: PaymentApi;
  readonly paymentsApiInbound: PaymentsApiInboundApi;
  readonly paymentsApiOutbound: PaymentsApiOutboundApi;
  readonly status: StatusApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.batch = new BatchApi(configuration);
    this.checkoutV2Generation = new CheckoutV2GenerationApi(configuration);
    this.checkoutGeneration = new CheckoutGenerationApi(configuration);
    this.files = new FilesApi(configuration);
    this.helpers = new HelpersApi(configuration);
    this.payment = new PaymentApi(configuration);
    this.paymentsApiInbound = new PaymentsApiInboundApi(configuration);
    this.paymentsApiOutbound = new PaymentsApiOutboundApi(configuration);
    this.status = new StatusApi(configuration);
  }

}
