/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Customer } from './customer';

/**
 * Optional object that can be used for billing or shipping information.
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * The door number, floor, building number, building name, and/or street name of the billing or shipping address.
     * @type {string}
     * @memberof Address
     */
    'street1'?: string;
    /**
     * The town, district, or city linked to billing or shipping.
     * @type {string}
     * @memberof Address
     */
    'city'?: string;
    /**
     * The county, state, or region of the billing address.
     * @type {string}
     * @memberof Address
     */
    'state'?: string;
    /**
     * The postal code or ZIP code of the address.
     * @type {string}
     * @memberof Address
     */
    'postalCode'?: string;
    /**
     * The country linked to billing or shipping as defined by ISO-3166-1 alpha-2.
     * @type {string}
     * @memberof Address
     */
    'country'?: string;
    /**
     * The customer\'s company name.
     * @type {string}
     * @memberof Address
     */
    'company'?: string;
    /**
     * Primary house number of the billing or shipping address.
     * @type {string}
     * @memberof Address
     */
    'houseNumber1'?: string;
    /**
     * The postal code or zip code of the billing or shipping address.
     * @type {string}
     * @memberof Address
     */
    'postcode'?: string;
    /**
     * Secondary house number of the billing or shipping address. Used when more addresses are bundled to the same primary house number. If present, houseNumber1 is mandatory.
     * @type {string}
     * @memberof Address
     */
    'street2'?: string;
    /**
     * 
     * @type {Customer}
     * @memberof Address
     */
    'customer'?: Customer;
}

