/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Authenticate requests using the userId, password, and entityId.
 * @export
 * @interface Authentication
 */
export interface Authentication {
    /**
     * Authentication userId.
     * @type {string}
     * @memberof Authentication
     */
    'userId': string;
    /**
     * Authentication password.
     * @type {string}
     * @memberof Authentication
     */
    'password': string;
    /**
     * Authentication entityId
     * @type {string}
     * @memberof Authentication
     */
    'entityId': string;
}

