/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Mandate } from './mandate';

/**
 * Customer bank account details.
 * @export
 * @interface Bank
 */
export interface Bank {
    /**
     * The bank account holder.
     * @type {string}
     * @memberof Bank
     */
    'holder'?: string;
    /**
     * The name of the bank which holds the account.
     * @type {string}
     * @memberof Bank
     */
    'bankName'?: string;
    /**
     * The bank account number.
     * @type {string}
     * @memberof Bank
     */
    'number'?: string;
    /**
     * The IBAN (International Bank Account Number) associated with the bank account.
     * @type {string}
     * @memberof Bank
     */
    'iban'?: string;
    /**
     * The BIC (Bank Identifier Code (SWIFT)) of the bank account.
     * @type {string}
     * @memberof Bank
     */
    'bic'?: string;
    /**
     * The code associated with the bank account.
     * @type {string}
     * @memberof Bank
     */
    'bankCode'?: string;
    /**
     * The country code of the bank account (ISO 3166-1).
     * @type {string}
     * @memberof Bank
     */
    'country'?: string;
    /**
     * 
     * @type {Mandate}
     * @memberof Bank
     */
    'mandate'?: Mandate;
    /**
     * The due date of the transaction of the direct debit.
     * @type {string}
     * @memberof Bank
     */
    'transactionDueDate'?: string;
}

