/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BatchGenerateLinkRequest
 */
export interface BatchGenerateLinkRequest {
    /**
     * The name of the CSV to be uploaded.
     * @type {string}
     * @memberof BatchGenerateLinkRequest
     */
    'filename': string;
    /**
     * Webhooks are sent to this URL. It overrides the generic merchant webhook URL.
     * @type {string}
     * @memberof BatchGenerateLinkRequest
     */
    'notificationUrl'?: string | null;
}

