/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface BatchResponse
 */
export interface BatchResponse {
    /**
     * Unique identifier for the payment attempt.
     * @type {string}
     * @memberof BatchResponse
     */
    'id': string;
    /**
     * Timestamp when the batch link was created.
     * @type {string}
     * @memberof BatchResponse
     */
    'createdAt': string;
    /**
     * Timestamp when the batch link was updated.
     * @type {string}
     * @memberof BatchResponse
     */
    'updatedAt': string;
    /**
     * The entity for the request.
     * @type {string}
     * @memberof BatchResponse
     */
    'entityId': string;
    /**
     * The name of the file that was uploaded.
     * @type {string}
     * @memberof BatchResponse
     */
    'filename': string;
    /**
     * Payment link status.
     * @type {string}
     * @memberof BatchResponse
     */
    'status': BatchResponseStatusEnum;
    /**
     * The amount of successfully created payment links.
     * @type {number}
     * @memberof BatchResponse
     */
    'successfulRows': number;
    /**
     * The total amount of rows parsed from file.
     * @type {number}
     * @memberof BatchResponse
     */
    'totalRows': number;
    /**
     * The error code will only be returned if the file fails to upload.
     * @type {string}
     * @memberof BatchResponse
     */
    'errorCode'?: string;
}

type BatchResponseStatusEnum = 'initiated' | 'processing' | 'completed' | 'error'


