/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Card details schema.
 * @export
 * @interface Card
 */
export interface Card {
    /**
     * The first six digits of the card number.
     * @type {string}
     * @memberof Card
     */
    'bin'?: string;
    /**
     * The last four digits of the card number.
     * @type {string}
     * @memberof Card
     */
    'last4Digits'?: string;
    /**
     * The card account holder.
     * @type {string}
     * @memberof Card
     */
    'holder'?: string;
    /**
     * The expiry month of the card.
     * @type {string}
     * @memberof Card
     */
    'expiryMonth'?: string;
    /**
     * The expiry year of the card.
     * @type {string}
     * @memberof Card
     */
    'expiryYear'?: string;
    /**
     * The type of card.
     * @type {string}
     * @memberof Card
     */
    'type'?: string;
}

