/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CartCartItemsInner } from './cart-cart-items-inner';

/**
 * Customer cart data.
 * @export
 * @interface Cart
 */
export interface Cart {
    /**
     * List of details of the items in the cart.
     * @type {Array<CartCartItemsInner>}
     * @memberof Cart
     */
    'cartItems'?: Array<CartCartItemsInner>;
    /**
     * The tax percentage or amount applied to the price of the items in the shopping cart.
     * @type {string}
     * @memberof Cart
     */
    'tax'?: string;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof Cart
     */
    'shippingAmount'?: string;
    /**
     * The discount percentage applied to the price of the items in the shopping cart.
     * @type {string}
     * @memberof Cart
     */
    'discount'?: string;
}

