/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CartCartItemsInner
 */
export interface CartCartItemsInner {
    /**
     * The description of the item in the shopping cart.
     * @type {string}
     * @memberof CartCartItemsInner
     */
    'description'?: string;
    /**
     * The name of the item in the shopping cart.
     * @type {string}
     * @memberof CartCartItemsInner
     */
    'name'?: string;
    /**
     * The unique identifier of the item in the shopping cart.
     * @type {string}
     * @memberof CartCartItemsInner
     */
    'merchantItemId'?: string;
    /**
     * The number of items in the shopping cart.
     * @type {number}
     * @memberof CartCartItemsInner
     */
    'quantity'?: number;
    /**
     * The price of the item in the shopping cart.
     * @type {string}
     * @memberof CartCartItemsInner
     */
    'price'?: string;
    /**
     * The weight (in kg) of the item in the shopping cart.
     * @type {number}
     * @memberof CartCartItemsInner
     */
    'weightInKg'?: number;
    /**
     * The category of the item in the shopping cart.
     * @type {string}
     * @memberof CartCartItemsInner
     */
    'category'?: string;
}

