/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutBaseWebhook } from './checkout-base-webhook';
import { CheckoutPendingWebhookAllOf } from './checkout-pending-webhook-all-of';

/**
 * @type CheckoutPendingWebhook
 * Webhook sent when a transaction is created on a checkout instance.
 * @export
 */
export type CheckoutPendingWebhook = CheckoutBaseWebhook & CheckoutPendingWebhookAllOf;


