/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutStateAllOf
 */
export interface CheckoutStateAllOf {
    /**
     * Registration ID added if tokeniseCard is true on card payment.
     * @type {string}
     * @memberof CheckoutStateAllOf
     */
    'registrationId'?: string;
    /**
     * Checkout ID of payment.
     * @type {string}
     * @memberof CheckoutStateAllOf
     */
    'checkoutId'?: string;
    /**
     * Unique transaction ID of payment.
     * @type {string}
     * @memberof CheckoutStateAllOf
     */
    'transactionUniqueId'?: string;
    /**
     * Result code returned for payment.
     * @type {string}
     * @memberof CheckoutStateAllOf
     */
    'resultCode'?: string;
    /**
     * Payment brand used for payment.
     * @type {string}
     * @memberof CheckoutStateAllOf
     */
    'paymentBrand'?: string;
}

