/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The base model for webhooks.
 * @export
 * @interface CheckoutBaseWebhook
 */
export interface CheckoutBaseWebhook {
    /**
     * The amount of the payment request. The period is used as the decimal separator. M-PESA does not support decimal amounts, so Checkout automatically rounds them up.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'amount'?: string;
    /**
     * Checkout ID.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'checkoutId'?: string;
    /**
     * The currency code of the payment request amount.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'currency'?: CheckoutBaseWebhookCurrencyEnum;
    /**
     * Merchant-provided reference number unique for your transactions.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'merchantTransactionId'?: string;
    /**
     * The payment type for the request.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'paymentType'?: CheckoutBaseWebhookPaymentTypeEnum;
    /**
     * A code representing the checkout state.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'result.code'?: string;
    /**
     * A friendly message.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'result.description'?: string;
    /**
     * Token to verify the integrity of the webhook, ensuring the request is coming from Checkout.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'signature'?: string;
    /**
     * Date and time when the webhook was sent.
     * @type {string}
     * @memberof CheckoutBaseWebhook
     */
    'timestamp'?: string;
}

type CheckoutBaseWebhookCurrencyEnum = 'ZAR' | 'USD' | 'KES' | 'MUR' | 'GBP' | 'EUR'
type CheckoutBaseWebhookPaymentTypeEnum = 'DB'


