/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The checkout object contains the default payment method and whether to tokenise the card number.
 * @export
 * @interface CheckoutOptions
 */
export interface CheckoutOptions {
    /**
     * The default payment method to show when Checkout loads.
     * @type {string}
     * @memberof CheckoutOptions
     */
    'defaultPaymentMethod'?: string | null;
    /**
     * Force the default payment method to be the only payment method.
     * @type {boolean}
     * @memberof CheckoutOptions
     */
    'forceDefaultMethod'?: boolean | null;
    /**
     * Tokenise the card number to allow it to be stored.
     * @type {boolean}
     * @memberof CheckoutOptions
     */
    'tokeniseCard'?: boolean;
}

