/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutBaseWebhook } from './checkout-base-webhook';
import { CheckoutCreatedWebhookAllOf } from './checkout-created-webhook-all-of';

/**
 * @type CheckoutCreatedWebhook
 * Webhook sent when a checkout instance is created.
 * @export
 */
export type CheckoutCreatedWebhook = CheckoutBaseWebhook & CheckoutCreatedWebhookAllOf;


