/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutV2Billing } from './checkout-v2-billing';
import { CheckoutV2Customer } from './checkout-v2-customer';
import { CheckoutV2Shipping } from './checkout-v2-shipping';

/**
 * 
 * @export
 * @interface CheckoutV2
 */
export interface CheckoutV2 {
    /**
     * The entity for the request. By default, this is the channel ID.
     * @type {string}
     * @memberof CheckoutV2
     */
    'authentication.entityId': string;
    /**
     * Merchant-provided reference number unique for your transactions.
     * @type {string}
     * @memberof CheckoutV2
     */
    'merchantTransactionId': string;
    /**
     * The amount of the payment request. The period is used as the decimal separator.  M-PESA does not support decimal amounts, so Checkout automatically rounds them up. 
     * @type {number}
     * @memberof CheckoutV2
     */
    'amount': number;
    /**
     * The currency code of the payment request amount.
     * @type {string}
     * @memberof CheckoutV2
     */
    'currency': CheckoutV2CurrencyEnum;
    /**
     * Unique value to represent each request.
     * @type {string}
     * @memberof CheckoutV2
     */
    'nonce': string;
    /**
     * Checkout uses a POST request to redirect the customer to this URL after the customer completes checkout. Must be a valid URL that can be accessed through a browser.
     * @type {string}
     * @memberof CheckoutV2
     */
    'shopperResultUrl': string;
    /**
     * The preferred payment method which is active in the checkout page at the point of redirecting.
     * @type {string}
     * @memberof CheckoutV2
     */
    'defaultPaymentMethod'?: CheckoutV2DefaultPaymentMethodEnum;
    /**
     * Force the default payment method to be the only payment method.
     * @type {boolean}
     * @memberof CheckoutV2
     */
    'forceDefaultMethod'?: boolean;
    /**
     * Merchant-provided invoice number unique for your transactions. This identifier is not sent onwards.
     * @type {string}
     * @memberof CheckoutV2
     */
    'merchantInvoiceId'?: string;
    /**
     * The customer is redirected to this URL if they cancel checkout. It must be a valid URL that can be reached through a browser.
     * @type {string}
     * @memberof CheckoutV2
     */
    'cancelUrl'?: string;
    /**
     * Override the preconfigured webhook URL for this checkout instance, any changes to checkout send a webhook to this URL.
     * @type {string}
     * @memberof CheckoutV2
     */
    'notificationUrl'?: string;
    /**
     * A name value pair used for sending custom information.
     * @type {{ [key: string]: string; }}
     * @memberof CheckoutV2
     */
    'customParameters'?: { [key: string]: string; };
    /**
     * 
     * @type {CheckoutV2Customer}
     * @memberof CheckoutV2
     */
    'customer'?: CheckoutV2Customer;
    /**
     * 
     * @type {CheckoutV2Billing}
     * @memberof CheckoutV2
     */
    'billing'?: CheckoutV2Billing;
    /**
     * 
     * @type {CheckoutV2Shipping}
     * @memberof CheckoutV2
     */
    'shipping'?: CheckoutV2Shipping;
    /**
     * Used to enable card tokenisation with COPYandPAY.
     * @type {boolean}
     * @memberof CheckoutV2
     */
    'createRegistration'?: boolean;
    /**
     * Used to provide a name for the application that is creating the checkout instance.
     * @type {string}
     * @memberof CheckoutV2
     */
    'originator'?: string;
    /**
     * Text to display on \"Return to Store\" button on completing checkout.
     * @type {string}
     * @memberof CheckoutV2
     */
    'returnTo'?: CheckoutV2ReturnToEnum;
}

type CheckoutV2CurrencyEnum = 'ZAR' | 'USD' | 'KES' | 'MUR' | 'GBP' | 'EUR'
type CheckoutV2DefaultPaymentMethodEnum = 'CARD' | 'MASTERPASS' | 'MOBICRED' | 'EFTSECURE' | 'MPESA' | '1FORYOU' | 'APLUS' | 'PAYPAL' | 'ZEROPAY' | 'PAYFLEX' | 'FINCHOICEPAY' | 'BLINKBYEMTEL' | 'CAPITECPAY' | 'NEDBANKDIRECTEFT' | 'PAYBYBANK' | 'MCBJUICE'
type CheckoutV2ReturnToEnum = 'STORE' | 'INVOICE'


