/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutSuccessfulWebhookAllOf
 */
export interface CheckoutSuccessfulWebhookAllOf {
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'merchant.name'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'recon.authCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'recon.resultCode'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'recon.rrn'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'result.code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'result.description'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'resultDetails.AcquirerResponse'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'resultDetails.ConnectorTxID1'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutSuccessfulWebhookAllOf
     */
    'resultDetails.ExtendedDescription'?: string;
}

