/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutPendingWebhookAllOf
 */
export interface CheckoutPendingWebhookAllOf {
    /**
     * The transaction ID.
     * @type {string}
     * @memberof CheckoutPendingWebhookAllOf
     */
    'id'?: string;
    /**
     * The payment method which the customer is paying with.
     * @type {string}
     * @memberof CheckoutPendingWebhookAllOf
     */
    'paymentBrand'?: CheckoutPendingWebhookAllOfPaymentBrandEnum;
    /**
     * 
     * @type {string}
     * @memberof CheckoutPendingWebhookAllOf
     */
    'result.code'?: string;
    /**
     * 
     * @type {string}
     * @memberof CheckoutPendingWebhookAllOf
     */
    'result.description'?: string;
}

type CheckoutPendingWebhookAllOfPaymentBrandEnum = 'VISA' | 'MASTERCARD' | 'DINERS CLUB' | 'AMERICAN EXPRESS' | 'MASTERPASS' | 'MOBICRED' | 'EFTSECURE' | 'MPESA' | '1FORYOU' | 'APLUS' | 'PAYPAL' | 'ZEROPAY' | 'PAYFLEX' | 'FINCHOICEPAY' | 'BLINKBYEMTEL' | 'CAPITECPAY' | 'NEDBANKDIRECTEFT' | 'PAYBYBANK' | 'MCBJUICE'


