/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RedirectPostData } from './redirect-post-data';

/**
 * 
 * @export
 * @interface CheckoutStatus
 */
export interface CheckoutStatus {
    /**
     * The status of the object.
     * @type {string}
     * @memberof CheckoutStatus
     */
    'status'?: string;
    /**
     * The remaining time, in seconds, of the checkout instance.
     * @type {string}
     * @memberof CheckoutStatus
     */
    'timestamp'?: string;
    /**
     * Redirect URL for Checkout.
     * @type {string}
     * @memberof CheckoutStatus
     */
    'redirect_url'?: string;
    /**
     * 
     * @type {RedirectPostData}
     * @memberof CheckoutStatus
     */
    'redirect_post_data'?: RedirectPostData;
}

