/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface CheckoutV2Customer
 */
export interface CheckoutV2Customer {
    /**
     * An identifier for this customer. Typically this is the ID that identifies the shopper in the shop\'s system.
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'merchantCustomerId'?: string;
    /**
     * The customer\'s first name or given name. Required if you send in any other customer parameters, also required for some risk checks and payment providers. Truncated after 48 characters.  Peach Payments recommends including the name so that it displays in the Peach Dashboard and is available for subsequent queries. 
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'givenName'?: string;
    /**
     * The customer\'s last name or surname. Required if you send in any other customer parameters, also required for some risk checks and payment providers. Truncated after 48 characters.  Peach Payments recommends including the surname so that it displays in the Peach Dashboard and is available for subsequent queries. 
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'surname'?: string;
    /**
     * The customer\'s mobile number.
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'mobile'?: string;
    /**
     * The customer\'s email address.
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'email'?: string;
    /**
     * The customer\'s ID number, required for high-risk merchants supporting Capitec Pay.
     * @type {string}
     * @memberof CheckoutV2Customer
     */
    'idNumber'?: string;
}

