/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The customer\'s browser details.
 * @export
 * @interface CustomerBrowser
 */
export interface CustomerBrowser {
    /**
     * The value of the accept header sent from the customer\'s browser.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'acceptHeader'?: string;
    /**
     * The value representing the browser language as defined in IETF BCP47.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'language'?: string;
    /**
     * The total height of the customer\'s screen in pixels.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'screenHeight'?: string;
    /**
     * The total width of the customer\'s screen in pixels.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'screenWidth'?: string;
    /**
     * The time-zone offset in minutes between UTC and the local time of the customer\'s browser.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'timezone'?: string;
    /**
     * The exact content of the HTTP user-agent header.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'userAgent'?: string;
    /**
     * The boolean that represents the ability of the customer\'s browser to execute Java.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'javaEnabled'?: string;
    /**
     * The boolean that represents the ability of the customer\'s browser to execute JavaScript.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'javascriptEnabled'?: string;
    /**
     * The value representing the bit depth of the colour palette for displaying images in bits per pixel.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'screenColorDepth'?: string;
    /**
     * The dimensions of the challenge window that has been displayed to the customer.
     * @type {string}
     * @memberof CustomerBrowser
     */
    'challengeWindow'?: string;
}

