/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { CustomerBrowser } from './customer-browser';

/**
 * Optional object sent if customer data is required.
 * @export
 * @interface Customer
 */
export interface Customer {
    /**
     * The customer\'s first name or given name. Peach Payments recommends including the name so that it displays in the Peach Dashboard and is available for subsequent queries.
     * @type {string}
     * @memberof Customer
     */
    'givenName': string;
    /**
     * The customer\'s last name or surname. Peach Payments recommends including the surname so that it displays in the Peach Dashboard and is available for subsequent queries.
     * @type {string}
     * @memberof Customer
     */
    'surname'?: string;
    /**
     * The customer\'s email  address.
     * @type {string}
     * @memberof Customer
     */
    'email'?: string;
    /**
     * The customer\'s mobile phone number.
     * @type {string}
     * @memberof Customer
     */
    'mobile'?: string;
    /**
     * The customer\'s WhatsApp number. Required for communicating with customers regarding payment. Format should be +27123456789. Required if sendWhatsapp is true.
     * @type {string}
     * @memberof Customer
     */
    'whatsapp'?: string;
    /**
     * 
     * @type {Address}
     * @memberof Customer
     */
    'billing'?: Address;
    /**
     * The customer\'s fax number, if provided.
     * @type {string}
     * @memberof Customer
     */
    'fax'?: string;
    /**
     * The customer\'s phone number.
     * @type {string}
     * @memberof Customer
     */
    'phone'?: string;
    /**
     * The customer\'s IP address.
     * @type {string}
     * @memberof Customer
     */
    'ip'?: string;
    /**
     * The language used for the customer on the merchant\'s site.
     * @type {string}
     * @memberof Customer
     */
    'merchantCustomerLanguage'?: string;
    /**
     * Used to determine if this is a new or returning customer.
     * @type {string}
     * @memberof Customer
     */
    'status'?: string;
    /**
     * The customer\'s ID on the merchant\'s site.
     * @type {string}
     * @memberof Customer
     */
    'merchantCustomerId'?: string;
    /**
     * The customer\'s tax ID, if required.
     * @type {string}
     * @memberof Customer
     */
    'taxId'?: string;
    /**
     * The customer\'s tax type, if required.
     * @type {string}
     * @memberof Customer
     */
    'taxType'?: string;
    /**
     * The customer\'s birth date.
     * @type {string}
     * @memberof Customer
     */
    'birthDate'?: string;
    /**
     * 
     * @type {CustomerBrowser}
     * @memberof Customer
     */
    'browser'?: CustomerBrowser;
}

