/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentBrand } from './payment-brand';
import { PaymentType } from './payment-type';
import { Result } from './result';
import { ResultDetails } from './result-details';

/**
 * Error object describing the error.
 * @export
 * @interface ErrorResponse
 */
export interface ErrorResponse {
    /**
     * 
     * @type {Result}
     * @memberof ErrorResponse
     */
    'result': Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof ErrorResponse
     */
    'resultDetails'?: ResultDetails;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof ErrorResponse
     */
    'timestamp': string;
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof ErrorResponse
     */
    'id'?: string;
    /**
     * Payment type of the transaction.
     * @type {PaymentType}
     * @memberof ErrorResponse
     */
    'paymentType'?: PaymentType;
    /**
     * The payment brand specifies the method of payment for the request.
     * @type {PaymentBrand}
     * @memberof ErrorResponse
     */
    'paymentBrand'?: PaymentBrand;
    /**
     * A JSON object depicting custom information sent by the merchant. Echoed back in the response.
     * @type {object}
     * @memberof ErrorResponse
     */
    'customParameters'?: object;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof ErrorResponse
     */
    'amount'?: string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof ErrorResponse
     */
    'currency'?: string;
}

