/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Error400Result } from './error400-result';
import { ResultDetails } from './result-details';

/**
 * Error object describing the 400 status code error.
 * @export
 * @interface Error400Response
 */
export interface Error400Response {
    /**
     * 
     * @type {Error400Result}
     * @memberof Error400Response
     */
    'result': Error400Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof Error400Response
     */
    'resultDetails'?: ResultDetails;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof Error400Response
     */
    'timestamp': string;
}

