/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutOptions } from './checkout-options';
import { Customer } from './customer';
import { GenerateLinkPaymentPayment } from './generate-link-payment-payment';
import { PaymentOptions } from './payment-options';

/**
 * 
 * @export
 * @interface GenerateLinkPayment
 */
export interface GenerateLinkPayment {
    /**
     * 
     * @type {GenerateLinkPaymentPayment}
     * @memberof GenerateLinkPayment
     */
    'payment': GenerateLinkPaymentPayment;
    /**
     * 
     * @type {Customer}
     * @memberof GenerateLinkPayment
     */
    'customer': Customer;
    /**
     * 
     * @type {PaymentOptions}
     * @memberof GenerateLinkPayment
     */
    'options': PaymentOptions;
    /**
     * 
     * @type {CheckoutOptions}
     * @memberof GenerateLinkPayment
     */
    'checkout': CheckoutOptions;
}

