/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The payment object contains the payment details, files, and notes for the payment link.
 * @export
 * @interface GenerateLinkPaymentPayment
 */
export interface GenerateLinkPaymentPayment {
    /**
     * Invoice ID that can be used to link the payment to an invoice on the merchant\'s system. Must be less than 17 characters.
     * @type {string}
     * @memberof GenerateLinkPaymentPayment
     */
    'merchantInvoiceId': string;
    /**
     * Payment amount. Must be positive and less than 1000000.00.
     * @type {number}
     * @memberof GenerateLinkPaymentPayment
     */
    'amount': number;
    /**
     * The currency code of the payment request amount (ISO 4217).
     * @type {string}
     * @memberof GenerateLinkPaymentPayment
     */
    'currency': GenerateLinkPaymentPaymentCurrencyEnum;
    /**
     * Files to attach to the payment link.
     * @type {Array<string>}
     * @memberof GenerateLinkPaymentPayment
     */
    'files'?: Array<string>;
    /**
     * A note to include with the payment link.
     * @type {string}
     * @memberof GenerateLinkPaymentPayment
     */
    'notes'?: string;
}

type GenerateLinkPaymentPaymentCurrencyEnum = 'ZAR' | 'KES' | 'USD'


