/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Customer mandate to bank.
 * @export
 * @interface Mandate
 */
export interface Mandate {
    /**
     * The date the direct debit mandate was signed.
     * @type {string}
     * @memberof Mandate
     */
    'dateOfSignature'?: string;
    /**
     * The ID of the direct debit mandate.
     * @type {string}
     * @memberof Mandate
     */
    'id'?: string;
    /**
     * The mandate reference for direct debit as a contractual agreement between the creditor and the debtor.
     * @type {string}
     * @memberof Mandate
     */
    'reference'?: string;
}

