/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Merchant object with data relevant to an EFTsecure transaction.
 * @export
 * @interface MerchantWebhookDataPayloadMerchant
 */
export interface MerchantWebhookDataPayloadMerchant {
    /**
     * 
     * @type {string}
     * @memberof MerchantWebhookDataPayloadMerchant
     */
    'apiUsername'?: string;
    /**
     * 
     * @type {string}
     * @memberof MerchantWebhookDataPayloadMerchant
     */
    'eftId'?: string;
}

