/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Bank account data.
 * @export
 * @interface MerchantWebhookDataPayloadBankAccount
 */
export interface MerchantWebhookDataPayloadBankAccount {
    /**
     * Name of bank account holder.
     * @type {string}
     * @memberof MerchantWebhookDataPayloadBankAccount
     */
    'holder': string;
    /**
     * Code associated with bank account.
     * @type {string}
     * @memberof MerchantWebhookDataPayloadBankAccount
     */
    'code'?: string;
    /**
     * Name of bank.
     * @type {string}
     * @memberof MerchantWebhookDataPayloadBankAccount
     */
    'bankName': string;
}

