/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { Card } from './card';
import { Customer } from './customer';
import { MerchantWebhookDataPayloadAuthentication } from './merchant-webhook-data-payload-authentication';
import { MerchantWebhookDataPayloadBankAccount } from './merchant-webhook-data-payload-bank-account';
import { MerchantWebhookDataPayloadMerchant } from './merchant-webhook-data-payload-merchant';
import { PaymentType } from './payment-type';
import { Recon } from './recon';
import { Result } from './result';
import { ResultDetails } from './result-details';
import { Shopify } from './shopify';

/**
 * The webhook data schema after decryption.
 * @export
 * @interface MerchantWebhookDataPayload
 */
export interface MerchantWebhookDataPayload {
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'id': string;
    /**
     * Payment type of the transaction.
     * @type {PaymentType}
     * @memberof MerchantWebhookDataPayload
     */
    'paymentType': PaymentType;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'amount': string;
    /**
     * The merchant\'s invoice ID.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'merchantInvoiceId': string;
    /**
     * Merchant account ID.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'merchantAccountId': string;
    /**
     * 
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'descriptor'?: string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'currency': string;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'presentationAmount': string;
    /**
     * 
     * @type {Result}
     * @memberof MerchantWebhookDataPayload
     */
    'result': Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof MerchantWebhookDataPayload
     */
    'resultDetails': ResultDetails;
    /**
     * The unique transaction identifier provided by the payment service provider.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'connectorTxID1': string;
    /**
     * 
     * @type {MerchantWebhookDataPayloadAuthentication}
     * @memberof MerchantWebhookDataPayload
     */
    'authentication': MerchantWebhookDataPayloadAuthentication;
    /**
     * 
     * @type {Card}
     * @memberof MerchantWebhookDataPayload
     */
    'card': Card;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'timestamp': string;
    /**
     * 
     * @type {Customer}
     * @memberof MerchantWebhookDataPayload
     */
    'customer'?: Customer;
    /**
     * 
     * @type {Address}
     * @memberof MerchantWebhookDataPayload
     */
    'shipping': Address;
    /**
     * 
     * @type {Address}
     * @memberof MerchantWebhookDataPayload
     */
    'billing': Address;
    /**
     * 
     * @type {Recon}
     * @memberof MerchantWebhookDataPayload
     */
    'recon'?: Recon;
    /**
     * 
     * @type {MerchantWebhookDataPayloadBankAccount}
     * @memberof MerchantWebhookDataPayload
     */
    'bankAccount': MerchantWebhookDataPayloadBankAccount;
    /**
     * A JSON object depicting custom information sent by the merchant. Echoed back in the response.
     * @type {object}
     * @memberof MerchantWebhookDataPayload
     */
    'customParameters'?: object;
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof MerchantWebhookDataPayload
     */
    'referenceId': string;
    /**
     * 
     * @type {Shopify}
     * @memberof MerchantWebhookDataPayload
     */
    'shopify': Shopify;
    /**
     * 
     * @type {MerchantWebhookDataPayloadMerchant}
     * @memberof MerchantWebhookDataPayload
     */
    'merchant'?: MerchantWebhookDataPayloadMerchant;
}

