/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MerchantTransactionIdStatusResponsePaymentsInner } from './merchant-transaction-id-status-response-payments-inner';
import { Result } from './result';

/**
 * The response for the status request using merchantTransactionId as the query field.
 * @export
 * @interface MerchantTransactionIdStatusResponse
 */
export interface MerchantTransactionIdStatusResponse {
    /**
     * 
     * @type {Result}
     * @memberof MerchantTransactionIdStatusResponse
     */
    'result': Result;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof MerchantTransactionIdStatusResponse
     */
    'timestamp': string;
    /**
     * 
     * @type {Array<MerchantTransactionIdStatusResponsePaymentsInner>}
     * @memberof MerchantTransactionIdStatusResponse
     */
    'payments': Array<MerchantTransactionIdStatusResponsePaymentsInner>;
}

