/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Base webhook format for Payment Links.
 * @export
 * @interface PaymentLinkBaseWebhook
 */
export interface PaymentLinkBaseWebhook {
    /**
     * Payment ID.
     * @type {string}
     * @memberof PaymentLinkBaseWebhook
     */
    'paymentId'?: string;
    /**
     * Type of webhook, reflecting the status of the payment link.
     * @type {string}
     * @memberof PaymentLinkBaseWebhook
     */
    'status'?: PaymentLinkBaseWebhookStatusEnum;
}

type PaymentLinkBaseWebhookStatusEnum = 'initiated' | 'processing' | 'expired' | 'cancelled' | 'completed' | 'opened'


