/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentBrand } from './payment-brand';
import { PaymentType } from './payment-type';
import { Redirect } from './redirect';
import { Result } from './result';
import { ResultDetails } from './result-details';
import { VirtualAccount } from './virtual-account';

/**
 * 
 * @export
 * @interface PaymentResponse
 */
export interface PaymentResponse {
    /**
     * The payment request amount.
     * @type {string}
     * @memberof PaymentResponse
     */
    'amount': string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof PaymentResponse
     */
    'currency': string;
    /**
     * The payment brand specifies the method of payment for the request.
     * @type {PaymentBrand}
     * @memberof PaymentResponse
     */
    'paymentBrand': PaymentBrand;
    /**
     * Payment type of the transaction.
     * @type {PaymentType}
     * @memberof PaymentResponse
     */
    'paymentType': PaymentType;
    /**
     * 
     * @type {Result}
     * @memberof PaymentResponse
     */
    'result': Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof PaymentResponse
     */
    'resultDetails'?: ResultDetails;
    /**
     * 
     * @type {Redirect}
     * @memberof PaymentResponse
     */
    'redirect'?: Redirect;
    /**
     * The unique transaction identifier provided by the payment service provider.
     * @type {string}
     * @memberof PaymentResponse
     */
    'connectorTxID1'?: string;
    /**
     * Another unique transaction identifier provided by the payment service provider.
     * @type {string}
     * @memberof PaymentResponse
     */
    'connectorTxID2'?: string;
    /**
     * A JSON object depicting custom information sent by the merchant. Echoed back in the response.
     * @type {object}
     * @memberof PaymentResponse
     */
    'customParameters': object;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof PaymentResponse
     */
    'timestamp': string;
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof PaymentResponse
     */
    'id': string;
    /**
     * Merchant-provided reference number, often used for reconciliation.
     * @type {string}
     * @memberof PaymentResponse
     */
    'merchantTransactionId'?: string;
    /**
     * The merchant\'s invoice ID.
     * @type {string}
     * @memberof PaymentResponse
     */
    'merchantInvoiceId'?: string;
    /**
     * The Payments API redirects the user to this URL after processing the payment request.
     * @type {string}
     * @memberof PaymentResponse
     */
    'shopperResultUrl'?: string;
    /**
     * 
     * @type {VirtualAccount}
     * @memberof PaymentResponse
     */
    'virtualAccount'?: VirtualAccount;
    /**
     * The expiry timestamp of the transaction.
     * @type {string}
     * @memberof PaymentResponse
     */
    'transactionExpiryTimestamp'?: string;
}

