/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Export a filtered list of payment links. `offset` and `perPage` will be ignored. Requires that merchant filter is specified.
 * @export
 * @interface PaymentGetAllPaymentLinks200Response
 */
export interface PaymentGetAllPaymentLinks200Response {
    /**
     * A URL to download the exported file.
     * @type {string}
     * @memberof PaymentGetAllPaymentLinks200Response
     */
    'file'?: string;
}

