/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RefundPaymentType } from './refund-payment-type';
import { Result } from './result';

/**
 * 
 * @export
 * @interface PaymentsApiInboundRefundTransaction502Response
 */
export interface PaymentsApiInboundRefundTransaction502Response {
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'id': string;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'amount': string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'currency': string;
    /**
     * Refund type of the transaction.
     * @type {RefundPaymentType}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'paymentType': RefundPaymentType;
    /**
     * 
     * @type {Result}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'result': Result;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof PaymentsApiInboundRefundTransaction502Response
     */
    'timestamp': string;
}

