/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The options object contains all the communication preferences for the payment link.
 * @export
 * @interface PaymentOptions
 */
export interface PaymentOptions {
    /**
     * Indicates whether to send an email to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentOptions
     */
    'sendEmail'?: boolean;
    /**
     * Indicates whether to send an SMS to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentOptions
     */
    'sendSms'?: boolean;
    /**
     * Indicates whether to send a WhatsApp message to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentOptions
     */
    'sendWhatsapp'?: boolean;
    /**
     * List of comma-separated email addresses to CC.
     * @type {string}
     * @memberof PaymentOptions
     */
    'emailCc'?: string;
    /**
     * List of comma-separated email addresses to BCC.
     * @type {string}
     * @memberof PaymentOptions
     */
    'emailBcc'?: string;
    /**
     * Time in minutes until the link expires. By default, expiry time is set to 30 days, which is also the maximum expiry time.
     * @type {number}
     * @memberof PaymentOptions
     */
    'expiryTime'?: number;
    /**
     * Webhook notification URL for this payment. Overrides the default set on the merchant.
     * @type {string}
     * @memberof PaymentOptions
     */
    'notificationUrl'?: string;
}

