/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ErrorResponse } from './error-response';
import { PaymentBrand } from './payment-brand';
import { PaymentResponse } from './payment-response';
import { PaymentType } from './payment-type';
import { Redirect } from './redirect';
import { Result } from './result';
import { ResultDetails } from './result-details';
import { VirtualAccount } from './virtual-account';

/**
 * @type PaymentsApiInboundInitiateDebitTransactionResponse
 * @export
 */
export type PaymentsApiInboundInitiateDebitTransactionResponse = ErrorResponse | PaymentResponse;


