/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentResponseOptions
 */
export interface PaymentResponseOptions {
    /**
     * Indicates whether to send an email to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentResponseOptions
     */
    'sendEmail'?: boolean;
    /**
     * Indicates whether to send an SMS to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentResponseOptions
     */
    'sendSms'?: boolean;
    /**
     * Indicates whether to send a WhatsApp message to the customer after creating the payment link.
     * @type {boolean}
     * @memberof PaymentResponseOptions
     */
    'sendWhatsapp'?: boolean;
    /**
     * List of comma-separated email addresses to CC.
     * @type {string}
     * @memberof PaymentResponseOptions
     */
    'emailCc'?: string | null;
    /**
     * List of comma-separated email addresses to BCC.
     * @type {string}
     * @memberof PaymentResponseOptions
     */
    'emailBcc'?: string | null;
    /**
     * Webhook notification URL for this payment. Overrides the default set on the merchant.
     * @type {string}
     * @memberof PaymentResponseOptions
     */
    'notificationUrl'?: string;
}

