/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentBrand } from './payment-brand';
import { Refund200ErrorResponse } from './refund200-error-response';
import { RefundPaymentType } from './refund-payment-type';
import { RefundResponse } from './refund-response';
import { Result } from './result';
import { ResultDetails } from './result-details';

/**
 * @type PaymentsApiInboundRefundTransactionResponse
 * @export
 */
export type PaymentsApiInboundRefundTransactionResponse = RefundResponse | Refund200ErrorResponse;


