/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentLinkBaseWebhook } from './payment-link-base-webhook';
import { PaymentLinkCreatedWebhookAllOf } from './payment-link-created-webhook-all-of';

/**
 * @type PaymentLinkCreatedWebhook
 * Payment link created.
 * @export
 */
export type PaymentLinkCreatedWebhook = PaymentLinkBaseWebhook & PaymentLinkCreatedWebhookAllOf;


