/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentLinkCompletedWebhookAllOf
 */
export interface PaymentLinkCompletedWebhookAllOf {
    /**
     * 
     * @type {string}
     * @memberof PaymentLinkCompletedWebhookAllOf
     */
    'status'?: string;
    /**
     * Payment brand used to complete the payment.
     * @type {string}
     * @memberof PaymentLinkCompletedWebhookAllOf
     */
    'paymentBrand'?: PaymentLinkCompletedWebhookAllOfPaymentBrandEnum;
    /**
     * Card registration token, if tokeniseCard was set to true on initial request and paymentBrand is a card type.
     * @type {string}
     * @memberof PaymentLinkCompletedWebhookAllOf
     */
    'registrationId'?: string;
}

type PaymentLinkCompletedWebhookAllOfPaymentBrandEnum = 'VISA' | 'MASTERCARD' | 'DINERS CLUB' | 'AMERICAN EXPRESS' | 'MASTERPASS' | 'MOBICRED' | 'EFTSECURE' | 'MPESA' | '1FORYOU' | 'APLUS' | 'PAYPAL' | 'ZEROPAY' | 'PAYFLEX' | 'STITCHEFT' | 'FINCHOICEPAY' | 'BLINKBYEMTEL' | 'CAPITECPAY'


