/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PaymentGetAllPaymentLinksResponseMeta
 */
export interface PaymentGetAllPaymentLinksResponseMeta {
    /**
     * The amount of items to retrieve.
     * @type {number}
     * @memberof PaymentGetAllPaymentLinksResponseMeta
     */
    'perPage'?: number;
    /**
     * The offset from which to read data.
     * @type {number}
     * @memberof PaymentGetAllPaymentLinksResponseMeta
     */
    'offset'?: number;
    /**
     * The offset from which to read data on a subsequent request.
     * @type {number}
     * @memberof PaymentGetAllPaymentLinksResponseMeta
     */
    'nextOffset'?: number;
    /**
     * The total number of payment links returned by the filter criteria.
     * @type {number}
     * @memberof PaymentGetAllPaymentLinksResponseMeta
     */
    'total'?: number;
}

