/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentGetAllPaymentLinksResponseMeta } from './payment-get-all-payment-links-response-meta';
import { QueryStatusResponse } from './query-status-response';

/**
 * 
 * @export
 * @interface PaymentGetAllPaymentLinksResponse
 */
export interface PaymentGetAllPaymentLinksResponse {
    /**
     * 
     * @type {Array<QueryStatusResponse>}
     * @memberof PaymentGetAllPaymentLinksResponse
     */
    'payments'?: Array<QueryStatusResponse>;
    /**
     * 
     * @type {PaymentGetAllPaymentLinksResponseMeta}
     * @memberof PaymentGetAllPaymentLinksResponse
     */
    'meta'?: PaymentGetAllPaymentLinksResponseMeta;
}

