/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CheckoutState } from './checkout-state';
import { Customer } from './customer';
import { PaymentResponseOptions } from './payment-response-options';
import { QueryStatusResponsePayment } from './query-status-response-payment';
import { QueryStatusResponseTermsOfService } from './query-status-response-terms-of-service';

/**
 * 
 * @export
 * @interface QueryStatusResponse
 */
export interface QueryStatusResponse {
    /**
     * Payment ID.
     * @type {string}
     * @memberof QueryStatusResponse
     */
    'id'?: string;
    /**
     * 
     * @type {QueryStatusResponsePayment}
     * @memberof QueryStatusResponse
     */
    'payment'?: QueryStatusResponsePayment;
    /**
     * Source of the payment link.
     * @type {string}
     * @memberof QueryStatusResponse
     */
    'source'?: QueryStatusResponseSourceEnum;
    /**
     * Timestamp when the payment link was created.
     * @type {string}
     * @memberof QueryStatusResponse
     */
    'createdAt'?: string;
    /**
     * Timestamp when the payment link was last modified.
     * @type {string}
     * @memberof QueryStatusResponse
     */
    'updatedAt'?: string;
    /**
     * 
     * @type {Customer}
     * @memberof QueryStatusResponse
     */
    'customer'?: Customer;
    /**
     * 
     * @type {PaymentResponseOptions}
     * @memberof QueryStatusResponse
     */
    'options'?: PaymentResponseOptions;
    /**
     * 
     * @type {CheckoutState}
     * @memberof QueryStatusResponse
     */
    'checkout'?: CheckoutState;
    /**
     * 
     * @type {QueryStatusResponseTermsOfService}
     * @memberof QueryStatusResponse
     */
    'termsOfService'?: QueryStatusResponseTermsOfService;
}

type QueryStatusResponseSourceEnum = 'API' | 'Xero' | 'UI'


