/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Transaction reconciliation data.
 * @export
 * @interface Recon
 */
export interface Recon {
    /**
     * The payment service provider merchant number.
     * @type {string}
     * @memberof Recon
     */
    'ciMerchantNumber'?: string;
    /**
     * The reconciliation reference number from the payment service provider.
     * @type {string}
     * @memberof Recon
     */
    'rrn'?: string;
    /**
     * The authorisation code from the payment service provider.
     * @type {string}
     * @memberof Recon
     */
    'authCode'?: string;
    /**
     * The result code from the payment service provider.
     * @type {string}
     * @memberof Recon
     */
    'resultCode'?: string;
    /**
     * The STAN reference number from the payment service provider.
     * @type {string}
     * @memberof Recon
     */
    'stan'?: string;
}

