/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RedirectParametersInner } from './redirect-parameters-inner';

/**
 * The URL that the merchant must redirect the user to after the transaction has been created and is in a pending state. When the user is redirected, they can complete any actions required for that specific payment method.
 * @export
 * @interface Redirect
 */
export interface Redirect {
    /**
     * Array of parameter names and values for the redirect URL.
     * @type {Array<RedirectParametersInner>}
     * @memberof Redirect
     */
    'parameters': Array<RedirectParametersInner>;
    /**
     * The URL that the shopper must be redirected to in order to proceed.
     * @type {string}
     * @memberof Redirect
     */
    'url': string;
    /**
     * REST method used for redirection.
     * @type {string}
     * @memberof Redirect
     */
    'method': RedirectMethodEnum;
}

type RedirectMethodEnum = 'GET' | 'POST'


