/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface RedirectPostData
 */
export interface RedirectPostData {
    /**
     * The checkout amount.
     * @type {string}
     * @memberof RedirectPostData
     */
    'amount'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectPostData
     */
    'checkoutId'?: string;
    /**
     * The currency code of the payment request amount.
     * @type {string}
     * @memberof RedirectPostData
     */
    'currency'?: RedirectPostDataCurrencyEnum;
    /**
     * The merchant transaction ID set when creating the checkout.
     * @type {string}
     * @memberof RedirectPostData
     */
    'merchantTransactionId'?: string;
    /**
     * 
     * @type {string}
     * @memberof RedirectPostData
     */
    'paymentType'?: RedirectPostDataPaymentTypeEnum;
    /**
     * A code representing the transaction state.
     * @type {string}
     * @memberof RedirectPostData
     */
    'result.code'?: string;
    /**
     * A friendly message.
     * @type {string}
     * @memberof RedirectPostData
     */
    'result.description'?: string;
    /**
     * Date and time when the checkout was created.
     * @type {string}
     * @memberof RedirectPostData
     */
    'timestamp'?: string;
}

type RedirectPostDataCurrencyEnum = 'ZAR' | 'USD' | 'KES' | 'MUR' | 'GBP' | 'EUR'
type RedirectPostDataPaymentTypeEnum = 'DB'


