/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentBrand } from './payment-brand';
import { RefundPaymentType } from './refund-payment-type';
import { Result } from './result';
import { ResultDetails } from './result-details';

/**
 * 
 * @export
 * @interface RefundResponse
 */
export interface RefundResponse {
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof RefundResponse
     */
    'id': string;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof RefundResponse
     */
    'amount': string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof RefundResponse
     */
    'currency': string;
    /**
     * The payment brand specifies the method of payment for the request.
     * @type {PaymentBrand}
     * @memberof RefundResponse
     */
    'paymentBrand'?: PaymentBrand;
    /**
     * Refund type of the transaction.
     * @type {RefundPaymentType}
     * @memberof RefundResponse
     */
    'paymentType': RefundPaymentType;
    /**
     * 
     * @type {Result}
     * @memberof RefundResponse
     */
    'result': Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof RefundResponse
     */
    'resultDetails'?: ResultDetails;
    /**
     * The unique transaction identifier provided by the payment service provider.
     * @type {string}
     * @memberof RefundResponse
     */
    'connectorTxID1'?: string;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof RefundResponse
     */
    'timestamp': string;
    /**
     * A JSON object depicting custom information sent by the merchant. Echoed back in the response.
     * @type {object}
     * @memberof RefundResponse
     */
    'customParameters'?: object;
}

