/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Authentication } from './authentication';
import { RefundPaymentType } from './refund-payment-type';

/**
 * Refund a successful debit transaction.
 * @export
 * @interface RefundRequest
 */
export interface RefundRequest {
    /**
     * 
     * @type {Authentication}
     * @memberof RefundRequest
     */
    'authentication': Authentication;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof RefundRequest
     */
    'amount': string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof RefundRequest
     */
    'currency': string;
    /**
     * Refund type of the transaction.
     * @type {RefundPaymentType}
     * @memberof RefundRequest
     */
    'paymentType': RefundPaymentType;
}

