/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The card data structure holds information regarding a credit or debit card account.
 * @export
 * @interface ResponseCard
 */
export interface ResponseCard {
    /**
     * The first six digits of the card number.
     * @type {string}
     * @memberof ResponseCard
     */
    'bin'?: string;
    /**
     * The last four digits of the card number.
     * @type {string}
     * @memberof ResponseCard
     */
    'last4Digits'?: string;
    /**
     * The card account holder.
     * @type {string}
     * @memberof ResponseCard
     */
    'holder'?: string;
    /**
     * The expiry month of the card.
     * @type {string}
     * @memberof ResponseCard
     */
    'expiryMonth'?: string;
    /**
     * The expiry year of the card.
     * @type {string}
     * @memberof ResponseCard
     */
    'expiryYear'?: string;
}

