/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The Shopify object.
 * @export
 * @interface Shopify
 */
export interface Shopify {
    /**
     * The Shopify order ID.
     * @type {string}
     * @memberof Shopify
     */
    'orderId'?: string;
    /**
     * The Shopify account ID.
     * @type {string}
     * @memberof Shopify
     */
    'accountId'?: string;
    /**
     * The Shopify signature.
     * @type {string}
     * @memberof Shopify
     */
    'signature'?: string;
    /**
     * Shopify test mode.
     * @type {string}
     * @memberof Shopify
     */
    'testMode'?: string;
}

