/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StatusQueryPaymentStatusResponseAuditInner
 */
export interface StatusQueryPaymentStatusResponseAuditInner {
    /**
     * The previous status of the payment link.
     * @type {string}
     * @memberof StatusQueryPaymentStatusResponseAuditInner
     */
    'oldStatus'?: StatusQueryPaymentStatusResponseAuditInnerOldStatusEnum;
    /**
     * The new status of the payment link.
     * @type {string}
     * @memberof StatusQueryPaymentStatusResponseAuditInner
     */
    'newStatus'?: StatusQueryPaymentStatusResponseAuditInnerNewStatusEnum;
    /**
     * The UTC time that the status changed.
     * @type {string}
     * @memberof StatusQueryPaymentStatusResponseAuditInner
     */
    'timestamp'?: string;
}

type StatusQueryPaymentStatusResponseAuditInnerOldStatusEnum = 'none' | 'initiated' | 'processing' | 'expired' | 'cancelled' | 'completed'
type StatusQueryPaymentStatusResponseAuditInnerNewStatusEnum = 'initiated' | 'processing' | 'expired' | 'cancelled' | 'completed'


