/*
Payments API inbound

The Payments API enables you to do a custom integration with Peach Payments and thereby support multiple payment methods.

The version of the OpenAPI document: 2.0.0
Contact: support@peachpayments.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Bank } from './bank';
import { PaymentBrand } from './payment-brand';
import { PaymentType } from './payment-type';
import { Recon } from './recon';
import { ResponseCard } from './response-card';
import { Result } from './result';
import { ResultDetails } from './result-details';

/**
 * The response for the status request using transactionId as the query field.
 * @export
 * @interface TransactionIdStatusResponse
 */
export interface TransactionIdStatusResponse {
    /**
     * The unique transaction ID provided by Peach Payments.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'id': string;
    /**
     * Merchant-provided reference number, often used for reconciliation.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'merchantTransactionId': string;
    /**
     * The payment request amount.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'amount': string;
    /**
     * The currency code of the payment request amount as defined by ISO-4217.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'currency': string;
    /**
     * The payment brand specifies the method of payment for the request.
     * @type {PaymentBrand}
     * @memberof TransactionIdStatusResponse
     */
    'paymentBrand': PaymentBrand;
    /**
     * Payment type of the transaction.
     * @type {PaymentType}
     * @memberof TransactionIdStatusResponse
     */
    'paymentType': PaymentType;
    /**
     * 
     * @type {Result}
     * @memberof TransactionIdStatusResponse
     */
    'result': Result;
    /**
     * 
     * @type {ResultDetails}
     * @memberof TransactionIdStatusResponse
     */
    'resultDetails'?: ResultDetails;
    /**
     * The unique transaction identifier provided by the payment service provider.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'connectorTxID1': string;
    /**
     * The timestamp of the transaction.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'timestamp': string;
    /**
     * A JSON object depicting custom information sent by the merchant. Echoed back in the response.
     * @type {object}
     * @memberof TransactionIdStatusResponse
     */
    'customParameters': object;
    /**
     * The merchant\'s invoice ID.
     * @type {string}
     * @memberof TransactionIdStatusResponse
     */
    'merchantInvoiceId'?: string;
    /**
     * 
     * @type {Bank}
     * @memberof TransactionIdStatusResponse
     */
    'bank'?: Bank;
    /**
     * 
     * @type {ResponseCard}
     * @memberof TransactionIdStatusResponse
     */
    'card'?: ResponseCard;
    /**
     * 
     * @type {Recon}
     * @memberof TransactionIdStatusResponse
     */
    'recon'?: Recon;
}

